			
autocmd FileType java nmap <buffer> <F5> :w<bar> ! python /f/progvocab/repo/vim-extension/scripts/javaTemplates.py <cword>  >> % <CR>
autocmd FileType java nmap <buffer> <F5> :w<bar> ! python /f/progvocab/repo/vim-extension/scripts/javaTemplates.py <cword>  >> % <CR>
set autoread
function! Class()
    r~/.vim/templates/java/class.txt
endfunction
function! Main()
    r~/.vim/templates/java/main.txt
endfunction
function! SOP()
    r~/.vim/templates/java/sop.txt
endfunction
function! TryCatch()
    r~/.vim/templates/java/trycatch.txt
endfunction
function! Filter()
    r~/.vim/templates/java/filter.txt
endfunction
function! ToMap()
    r~/.vim/templates/java/toMap.txt
endfunction
function! JsSOP()
    r~/.vim/templates/javascript/sop.txt
endfunction
function! JsTryCatch()
    r~/.vim/templates/javascript/trycatch.txt
endfunction
function! ReactClassComponent()
    r~/.vim/templates/javascript/react/reactClassComponent.txt
endfunction
function! Pom()
    r~/.vim/templates/xml/pom.txt
endfunction
function! PhpMysqlConnection()
    r~/.vim/templates/php/mysqlConnection.txt
endfunction




